### ISSUE TITLE
Cannot Connect error messages

### ISSUE THREAD

**Issue by maxlxl** [s3inlc/holm#1]
Hi,
if I'm using HOLM to generate or update my files I get these error messages after each file processed:
`QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)`

The strange thing is that all works fine. But this messages are a bit confusing. Maybe you have an idea to fix this 'issue'.

Best, Max

**Comment by s3inlc** [comment]
Can you tell me some details about which OS you're running? 
And did you compile the code yourself or are you using the prebuilt binary?

**Comment by maxlxl** [comment]
I've used the precompiled Version HOLM-alpha v1.1 for win. I'm on Windows 7 x64.
I'll check if the error is present on Windows 10 and Ubuntu 16.04 on Monday and then report back to you.

**Comment by maxlxl** [comment]
First of all, sorry for that late answer. I got really busy the last days.
Okay, I compiled the Version for Ubuntu 16.04 and Debian 8 and all works fine. It seems to be a problem with Windows only. I think these messages are from another Qt Library that I have intstalled on my system. And because it's just a message without breaking anything, it can get maybe just ignored.
